echo:
	@echo "CXX = '$(CXX)', origin $(origin CXX)"
	@echo "exported      = '$(exported)', origin $(origin exported)"
	@echo "not_exported  = '$(not_exported)', origin $(origin not_exported)"
	@echo "cond_exported = '$(cond_exported)', origin $(origin cond_exported)"
